server:
  port: 9999
  context-path: /client
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8901/oauth/token
      user-authorization-uri: http://localhost:8901/oauth/authorize
    resource:
      user-info-uri: http://localhost:8901/me
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.divide2: DEBUG
spring:
  jpa:
    database: mysql
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/